include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    unnecessary_library_directive: ignore
    inference_failure_on_function_return_type: ignore

linter:
  rules:
    lines_longer_than_80_chars: true